export const carsObject = [

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: " is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFvSrT5gJCKsPIJKur9gwl5xB1YV9axVmNjL2vyS3_&s',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

]