export const carsObject = [

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: " is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },
    {
        id:"uniqueIsdhere",
        stars:5,
        trips:62,
        host:"All star host",
        name: "Tesla Model 3",
        likes:302,
        price: 20000,
        currency: "USD",
        image: 'https://wallpapercave.com/wp/wp4318749.jpg',
        description: "Ford 2022 is a new car from Ford company and it is a very good car. It has a a great engine of 8 pistols.",
    },

]